### PR TITLE
Update examples to use ulab.numpy

### LINKED ISSUE #14: example needs updating for CP 7.x
```
libraries/helpers/ble_adafruit/examples/ble_adafruit_feather_bluefruit_sense.py
90:mic_samples = ulab.zeros(MIC_NUM_SAMPLES, dtype=ulab.uint16)

libraries/helpers/ble_adafruit/examples/ble_adafruit_clue.py
64:mic_samples = ulab.zeros(MIC_NUM_SAMPLES, dtype=ulab.uint16)
```
these need to be updated to use `ulab.numpy`

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #14.

### CODE REVIEW

**Comment by rsbohn** [comment]
Should the example support CP6?

**Comment by rsbohn** [comment]
Looks good for CP 7.x.

**Comment by dhalbert** [comment]
> Should the example support CP6?

No, we are no longer making 6.x bundles, since 7.x has been out for a while and continuing with some compatibility code is difficult. There is a list of the last x.x bundles here: https://learn.adafruit.com/welcome-to-circuitpython/frequently-asked-questions#faq-3105289

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thank you @dhalbert 

tested successfully on CLUE 7.2.0 alpha 1

**Pull request merged**
