### PR TITLE
Fix Build CI issue

### PR DESCRIPTION
**Pull request by tekktrik**
See https://github.com/adafruit/Adafruit_CircuitPython_BLE_BroadcastNet/pull/29 for more information

### CODE REVIEW

**Comment by dhalbert** [comment]
Suppose you used :py:meth:`~mymodule.MyClass.mymethod`, would that work also? I'm trying to weigh the nuisance of that vs the exclusion you added. I could imagine excluding one thing, only to have yet another appear in its place.

sphinx is being too helpful here.

**Comment by tekktrik** [comment]
I could give that a shot when I get back to my dev laptop tonight!

**Comment by tekktrik** [comment]
Yup, that works!

**Comment by tekktrik** [comment]
Closing in favor of fixing `adafruit_ble`

**Pull request closed without merging**
